$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %O %S';
$clean_ext = 'synctex.gz acn acr alg aux bbl bcf fdb_latexmk fls log out run.xml toc nav snm vrb';
@default_files = ('presentazione.tex');
